
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NutritionApiResponse` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NutritionApiResponse
 * 
 */
export type NutritionApiResponseModel = runtime.Types.Result.DefaultSelection<Prisma.$NutritionApiResponsePayload>

export type AggregateNutritionApiResponse = {
  _count: NutritionApiResponseCountAggregateOutputType | null
  _avg: NutritionApiResponseAvgAggregateOutputType | null
  _sum: NutritionApiResponseSumAggregateOutputType | null
  _min: NutritionApiResponseMinAggregateOutputType | null
  _max: NutritionApiResponseMaxAggregateOutputType | null
}

export type NutritionApiResponseAvgAggregateOutputType = {
  itemCount: number | null
}

export type NutritionApiResponseSumAggregateOutputType = {
  itemCount: number | null
}

export type NutritionApiResponseMinAggregateOutputType = {
  id: string | null
  userId: string | null
  query: string | null
  itemCount: number | null
  createdAt: Date | null
}

export type NutritionApiResponseMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  query: string | null
  itemCount: number | null
  createdAt: Date | null
}

export type NutritionApiResponseCountAggregateOutputType = {
  id: number
  userId: number
  query: number
  rawResponse: number
  itemCount: number
  createdAt: number
  _all: number
}


export type NutritionApiResponseAvgAggregateInputType = {
  itemCount?: true
}

export type NutritionApiResponseSumAggregateInputType = {
  itemCount?: true
}

export type NutritionApiResponseMinAggregateInputType = {
  id?: true
  userId?: true
  query?: true
  itemCount?: true
  createdAt?: true
}

export type NutritionApiResponseMaxAggregateInputType = {
  id?: true
  userId?: true
  query?: true
  itemCount?: true
  createdAt?: true
}

export type NutritionApiResponseCountAggregateInputType = {
  id?: true
  userId?: true
  query?: true
  rawResponse?: true
  itemCount?: true
  createdAt?: true
  _all?: true
}

export type NutritionApiResponseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NutritionApiResponse to aggregate.
   */
  where?: Prisma.NutritionApiResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NutritionApiResponses to fetch.
   */
  orderBy?: Prisma.NutritionApiResponseOrderByWithRelationInput | Prisma.NutritionApiResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NutritionApiResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NutritionApiResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NutritionApiResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NutritionApiResponses
  **/
  _count?: true | NutritionApiResponseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NutritionApiResponseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NutritionApiResponseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NutritionApiResponseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NutritionApiResponseMaxAggregateInputType
}

export type GetNutritionApiResponseAggregateType<T extends NutritionApiResponseAggregateArgs> = {
      [P in keyof T & keyof AggregateNutritionApiResponse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNutritionApiResponse[P]>
    : Prisma.GetScalarType<T[P], AggregateNutritionApiResponse[P]>
}




export type NutritionApiResponseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NutritionApiResponseWhereInput
  orderBy?: Prisma.NutritionApiResponseOrderByWithAggregationInput | Prisma.NutritionApiResponseOrderByWithAggregationInput[]
  by: Prisma.NutritionApiResponseScalarFieldEnum[] | Prisma.NutritionApiResponseScalarFieldEnum
  having?: Prisma.NutritionApiResponseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NutritionApiResponseCountAggregateInputType | true
  _avg?: NutritionApiResponseAvgAggregateInputType
  _sum?: NutritionApiResponseSumAggregateInputType
  _min?: NutritionApiResponseMinAggregateInputType
  _max?: NutritionApiResponseMaxAggregateInputType
}

export type NutritionApiResponseGroupByOutputType = {
  id: string
  userId: string | null
  query: string
  rawResponse: runtime.JsonValue
  itemCount: number
  createdAt: Date
  _count: NutritionApiResponseCountAggregateOutputType | null
  _avg: NutritionApiResponseAvgAggregateOutputType | null
  _sum: NutritionApiResponseSumAggregateOutputType | null
  _min: NutritionApiResponseMinAggregateOutputType | null
  _max: NutritionApiResponseMaxAggregateOutputType | null
}

type GetNutritionApiResponseGroupByPayload<T extends NutritionApiResponseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NutritionApiResponseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NutritionApiResponseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NutritionApiResponseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NutritionApiResponseGroupByOutputType[P]>
      }
    >
  >



export type NutritionApiResponseWhereInput = {
  AND?: Prisma.NutritionApiResponseWhereInput | Prisma.NutritionApiResponseWhereInput[]
  OR?: Prisma.NutritionApiResponseWhereInput[]
  NOT?: Prisma.NutritionApiResponseWhereInput | Prisma.NutritionApiResponseWhereInput[]
  id?: Prisma.StringFilter<"NutritionApiResponse"> | string
  userId?: Prisma.StringNullableFilter<"NutritionApiResponse"> | string | null
  query?: Prisma.StringFilter<"NutritionApiResponse"> | string
  rawResponse?: Prisma.JsonFilter<"NutritionApiResponse">
  itemCount?: Prisma.IntFilter<"NutritionApiResponse"> | number
  createdAt?: Prisma.DateTimeFilter<"NutritionApiResponse"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type NutritionApiResponseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  query?: Prisma.SortOrder
  rawResponse?: Prisma.SortOrder
  itemCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type NutritionApiResponseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NutritionApiResponseWhereInput | Prisma.NutritionApiResponseWhereInput[]
  OR?: Prisma.NutritionApiResponseWhereInput[]
  NOT?: Prisma.NutritionApiResponseWhereInput | Prisma.NutritionApiResponseWhereInput[]
  userId?: Prisma.StringNullableFilter<"NutritionApiResponse"> | string | null
  query?: Prisma.StringFilter<"NutritionApiResponse"> | string
  rawResponse?: Prisma.JsonFilter<"NutritionApiResponse">
  itemCount?: Prisma.IntFilter<"NutritionApiResponse"> | number
  createdAt?: Prisma.DateTimeFilter<"NutritionApiResponse"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type NutritionApiResponseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  query?: Prisma.SortOrder
  rawResponse?: Prisma.SortOrder
  itemCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.NutritionApiResponseCountOrderByAggregateInput
  _avg?: Prisma.NutritionApiResponseAvgOrderByAggregateInput
  _max?: Prisma.NutritionApiResponseMaxOrderByAggregateInput
  _min?: Prisma.NutritionApiResponseMinOrderByAggregateInput
  _sum?: Prisma.NutritionApiResponseSumOrderByAggregateInput
}

export type NutritionApiResponseScalarWhereWithAggregatesInput = {
  AND?: Prisma.NutritionApiResponseScalarWhereWithAggregatesInput | Prisma.NutritionApiResponseScalarWhereWithAggregatesInput[]
  OR?: Prisma.NutritionApiResponseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NutritionApiResponseScalarWhereWithAggregatesInput | Prisma.NutritionApiResponseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"NutritionApiResponse"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"NutritionApiResponse"> | string | null
  query?: Prisma.StringWithAggregatesFilter<"NutritionApiResponse"> | string
  rawResponse?: Prisma.JsonWithAggregatesFilter<"NutritionApiResponse">
  itemCount?: Prisma.IntWithAggregatesFilter<"NutritionApiResponse"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NutritionApiResponse"> | Date | string
}

export type NutritionApiResponseCreateInput = {
  id?: string
  query: string
  rawResponse: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount: number
  createdAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutNutritionApiResponsesInput
}

export type NutritionApiResponseUncheckedCreateInput = {
  id?: string
  userId?: string | null
  query: string
  rawResponse: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount: number
  createdAt?: Date | string
}

export type NutritionApiResponseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  query?: Prisma.StringFieldUpdateOperationsInput | string
  rawResponse?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutNutritionApiResponsesNestedInput
}

export type NutritionApiResponseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  rawResponse?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NutritionApiResponseCreateManyInput = {
  id?: string
  userId?: string | null
  query: string
  rawResponse: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount: number
  createdAt?: Date | string
}

export type NutritionApiResponseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  query?: Prisma.StringFieldUpdateOperationsInput | string
  rawResponse?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NutritionApiResponseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  rawResponse?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NutritionApiResponseListRelationFilter = {
  every?: Prisma.NutritionApiResponseWhereInput
  some?: Prisma.NutritionApiResponseWhereInput
  none?: Prisma.NutritionApiResponseWhereInput
}

export type NutritionApiResponseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NutritionApiResponseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  rawResponse?: Prisma.SortOrder
  itemCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NutritionApiResponseAvgOrderByAggregateInput = {
  itemCount?: Prisma.SortOrder
}

export type NutritionApiResponseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  itemCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NutritionApiResponseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  itemCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NutritionApiResponseSumOrderByAggregateInput = {
  itemCount?: Prisma.SortOrder
}

export type NutritionApiResponseCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.NutritionApiResponseCreateWithoutUserInput, Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput> | Prisma.NutritionApiResponseCreateWithoutUserInput[] | Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NutritionApiResponseCreateOrConnectWithoutUserInput | Prisma.NutritionApiResponseCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.NutritionApiResponseCreateManyUserInputEnvelope
  connect?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
}

export type NutritionApiResponseUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.NutritionApiResponseCreateWithoutUserInput, Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput> | Prisma.NutritionApiResponseCreateWithoutUserInput[] | Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NutritionApiResponseCreateOrConnectWithoutUserInput | Prisma.NutritionApiResponseCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.NutritionApiResponseCreateManyUserInputEnvelope
  connect?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
}

export type NutritionApiResponseUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.NutritionApiResponseCreateWithoutUserInput, Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput> | Prisma.NutritionApiResponseCreateWithoutUserInput[] | Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NutritionApiResponseCreateOrConnectWithoutUserInput | Prisma.NutritionApiResponseCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.NutritionApiResponseUpsertWithWhereUniqueWithoutUserInput | Prisma.NutritionApiResponseUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.NutritionApiResponseCreateManyUserInputEnvelope
  set?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
  disconnect?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
  delete?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
  connect?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
  update?: Prisma.NutritionApiResponseUpdateWithWhereUniqueWithoutUserInput | Prisma.NutritionApiResponseUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.NutritionApiResponseUpdateManyWithWhereWithoutUserInput | Prisma.NutritionApiResponseUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.NutritionApiResponseScalarWhereInput | Prisma.NutritionApiResponseScalarWhereInput[]
}

export type NutritionApiResponseUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.NutritionApiResponseCreateWithoutUserInput, Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput> | Prisma.NutritionApiResponseCreateWithoutUserInput[] | Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NutritionApiResponseCreateOrConnectWithoutUserInput | Prisma.NutritionApiResponseCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.NutritionApiResponseUpsertWithWhereUniqueWithoutUserInput | Prisma.NutritionApiResponseUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.NutritionApiResponseCreateManyUserInputEnvelope
  set?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
  disconnect?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
  delete?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
  connect?: Prisma.NutritionApiResponseWhereUniqueInput | Prisma.NutritionApiResponseWhereUniqueInput[]
  update?: Prisma.NutritionApiResponseUpdateWithWhereUniqueWithoutUserInput | Prisma.NutritionApiResponseUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.NutritionApiResponseUpdateManyWithWhereWithoutUserInput | Prisma.NutritionApiResponseUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.NutritionApiResponseScalarWhereInput | Prisma.NutritionApiResponseScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NutritionApiResponseCreateWithoutUserInput = {
  id?: string
  query: string
  rawResponse: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount: number
  createdAt?: Date | string
}

export type NutritionApiResponseUncheckedCreateWithoutUserInput = {
  id?: string
  query: string
  rawResponse: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount: number
  createdAt?: Date | string
}

export type NutritionApiResponseCreateOrConnectWithoutUserInput = {
  where: Prisma.NutritionApiResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.NutritionApiResponseCreateWithoutUserInput, Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput>
}

export type NutritionApiResponseCreateManyUserInputEnvelope = {
  data: Prisma.NutritionApiResponseCreateManyUserInput | Prisma.NutritionApiResponseCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type NutritionApiResponseUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.NutritionApiResponseWhereUniqueInput
  update: Prisma.XOR<Prisma.NutritionApiResponseUpdateWithoutUserInput, Prisma.NutritionApiResponseUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.NutritionApiResponseCreateWithoutUserInput, Prisma.NutritionApiResponseUncheckedCreateWithoutUserInput>
}

export type NutritionApiResponseUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.NutritionApiResponseWhereUniqueInput
  data: Prisma.XOR<Prisma.NutritionApiResponseUpdateWithoutUserInput, Prisma.NutritionApiResponseUncheckedUpdateWithoutUserInput>
}

export type NutritionApiResponseUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.NutritionApiResponseScalarWhereInput
  data: Prisma.XOR<Prisma.NutritionApiResponseUpdateManyMutationInput, Prisma.NutritionApiResponseUncheckedUpdateManyWithoutUserInput>
}

export type NutritionApiResponseScalarWhereInput = {
  AND?: Prisma.NutritionApiResponseScalarWhereInput | Prisma.NutritionApiResponseScalarWhereInput[]
  OR?: Prisma.NutritionApiResponseScalarWhereInput[]
  NOT?: Prisma.NutritionApiResponseScalarWhereInput | Prisma.NutritionApiResponseScalarWhereInput[]
  id?: Prisma.StringFilter<"NutritionApiResponse"> | string
  userId?: Prisma.StringNullableFilter<"NutritionApiResponse"> | string | null
  query?: Prisma.StringFilter<"NutritionApiResponse"> | string
  rawResponse?: Prisma.JsonFilter<"NutritionApiResponse">
  itemCount?: Prisma.IntFilter<"NutritionApiResponse"> | number
  createdAt?: Prisma.DateTimeFilter<"NutritionApiResponse"> | Date | string
}

export type NutritionApiResponseCreateManyUserInput = {
  id?: string
  query: string
  rawResponse: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount: number
  createdAt?: Date | string
}

export type NutritionApiResponseUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  query?: Prisma.StringFieldUpdateOperationsInput | string
  rawResponse?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NutritionApiResponseUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  query?: Prisma.StringFieldUpdateOperationsInput | string
  rawResponse?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NutritionApiResponseUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  query?: Prisma.StringFieldUpdateOperationsInput | string
  rawResponse?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  itemCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type NutritionApiResponseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  query?: boolean
  rawResponse?: boolean
  itemCount?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.NutritionApiResponse$userArgs<ExtArgs>
}, ExtArgs["result"]["nutritionApiResponse"]>

export type NutritionApiResponseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  query?: boolean
  rawResponse?: boolean
  itemCount?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.NutritionApiResponse$userArgs<ExtArgs>
}, ExtArgs["result"]["nutritionApiResponse"]>

export type NutritionApiResponseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  query?: boolean
  rawResponse?: boolean
  itemCount?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.NutritionApiResponse$userArgs<ExtArgs>
}, ExtArgs["result"]["nutritionApiResponse"]>

export type NutritionApiResponseSelectScalar = {
  id?: boolean
  userId?: boolean
  query?: boolean
  rawResponse?: boolean
  itemCount?: boolean
  createdAt?: boolean
}

export type NutritionApiResponseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "query" | "rawResponse" | "itemCount" | "createdAt", ExtArgs["result"]["nutritionApiResponse"]>
export type NutritionApiResponseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.NutritionApiResponse$userArgs<ExtArgs>
}
export type NutritionApiResponseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.NutritionApiResponse$userArgs<ExtArgs>
}
export type NutritionApiResponseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.NutritionApiResponse$userArgs<ExtArgs>
}

export type $NutritionApiResponsePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NutritionApiResponse"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string | null
    query: string
    rawResponse: runtime.JsonValue
    itemCount: number
    createdAt: Date
  }, ExtArgs["result"]["nutritionApiResponse"]>
  composites: {}
}

export type NutritionApiResponseGetPayload<S extends boolean | null | undefined | NutritionApiResponseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload, S>

export type NutritionApiResponseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NutritionApiResponseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NutritionApiResponseCountAggregateInputType | true
  }

export interface NutritionApiResponseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NutritionApiResponse'], meta: { name: 'NutritionApiResponse' } }
  /**
   * Find zero or one NutritionApiResponse that matches the filter.
   * @param {NutritionApiResponseFindUniqueArgs} args - Arguments to find a NutritionApiResponse
   * @example
   * // Get one NutritionApiResponse
   * const nutritionApiResponse = await prisma.nutritionApiResponse.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NutritionApiResponseFindUniqueArgs>(args: Prisma.SelectSubset<T, NutritionApiResponseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NutritionApiResponseClient<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NutritionApiResponse that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NutritionApiResponseFindUniqueOrThrowArgs} args - Arguments to find a NutritionApiResponse
   * @example
   * // Get one NutritionApiResponse
   * const nutritionApiResponse = await prisma.nutritionApiResponse.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NutritionApiResponseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NutritionApiResponseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NutritionApiResponseClient<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NutritionApiResponse that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionApiResponseFindFirstArgs} args - Arguments to find a NutritionApiResponse
   * @example
   * // Get one NutritionApiResponse
   * const nutritionApiResponse = await prisma.nutritionApiResponse.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NutritionApiResponseFindFirstArgs>(args?: Prisma.SelectSubset<T, NutritionApiResponseFindFirstArgs<ExtArgs>>): Prisma.Prisma__NutritionApiResponseClient<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NutritionApiResponse that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionApiResponseFindFirstOrThrowArgs} args - Arguments to find a NutritionApiResponse
   * @example
   * // Get one NutritionApiResponse
   * const nutritionApiResponse = await prisma.nutritionApiResponse.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NutritionApiResponseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NutritionApiResponseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NutritionApiResponseClient<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NutritionApiResponses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionApiResponseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NutritionApiResponses
   * const nutritionApiResponses = await prisma.nutritionApiResponse.findMany()
   * 
   * // Get first 10 NutritionApiResponses
   * const nutritionApiResponses = await prisma.nutritionApiResponse.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const nutritionApiResponseWithIdOnly = await prisma.nutritionApiResponse.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NutritionApiResponseFindManyArgs>(args?: Prisma.SelectSubset<T, NutritionApiResponseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NutritionApiResponse.
   * @param {NutritionApiResponseCreateArgs} args - Arguments to create a NutritionApiResponse.
   * @example
   * // Create one NutritionApiResponse
   * const NutritionApiResponse = await prisma.nutritionApiResponse.create({
   *   data: {
   *     // ... data to create a NutritionApiResponse
   *   }
   * })
   * 
   */
  create<T extends NutritionApiResponseCreateArgs>(args: Prisma.SelectSubset<T, NutritionApiResponseCreateArgs<ExtArgs>>): Prisma.Prisma__NutritionApiResponseClient<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NutritionApiResponses.
   * @param {NutritionApiResponseCreateManyArgs} args - Arguments to create many NutritionApiResponses.
   * @example
   * // Create many NutritionApiResponses
   * const nutritionApiResponse = await prisma.nutritionApiResponse.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NutritionApiResponseCreateManyArgs>(args?: Prisma.SelectSubset<T, NutritionApiResponseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NutritionApiResponses and returns the data saved in the database.
   * @param {NutritionApiResponseCreateManyAndReturnArgs} args - Arguments to create many NutritionApiResponses.
   * @example
   * // Create many NutritionApiResponses
   * const nutritionApiResponse = await prisma.nutritionApiResponse.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NutritionApiResponses and only return the `id`
   * const nutritionApiResponseWithIdOnly = await prisma.nutritionApiResponse.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NutritionApiResponseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NutritionApiResponseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NutritionApiResponse.
   * @param {NutritionApiResponseDeleteArgs} args - Arguments to delete one NutritionApiResponse.
   * @example
   * // Delete one NutritionApiResponse
   * const NutritionApiResponse = await prisma.nutritionApiResponse.delete({
   *   where: {
   *     // ... filter to delete one NutritionApiResponse
   *   }
   * })
   * 
   */
  delete<T extends NutritionApiResponseDeleteArgs>(args: Prisma.SelectSubset<T, NutritionApiResponseDeleteArgs<ExtArgs>>): Prisma.Prisma__NutritionApiResponseClient<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NutritionApiResponse.
   * @param {NutritionApiResponseUpdateArgs} args - Arguments to update one NutritionApiResponse.
   * @example
   * // Update one NutritionApiResponse
   * const nutritionApiResponse = await prisma.nutritionApiResponse.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NutritionApiResponseUpdateArgs>(args: Prisma.SelectSubset<T, NutritionApiResponseUpdateArgs<ExtArgs>>): Prisma.Prisma__NutritionApiResponseClient<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NutritionApiResponses.
   * @param {NutritionApiResponseDeleteManyArgs} args - Arguments to filter NutritionApiResponses to delete.
   * @example
   * // Delete a few NutritionApiResponses
   * const { count } = await prisma.nutritionApiResponse.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NutritionApiResponseDeleteManyArgs>(args?: Prisma.SelectSubset<T, NutritionApiResponseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NutritionApiResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionApiResponseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NutritionApiResponses
   * const nutritionApiResponse = await prisma.nutritionApiResponse.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NutritionApiResponseUpdateManyArgs>(args: Prisma.SelectSubset<T, NutritionApiResponseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NutritionApiResponses and returns the data updated in the database.
   * @param {NutritionApiResponseUpdateManyAndReturnArgs} args - Arguments to update many NutritionApiResponses.
   * @example
   * // Update many NutritionApiResponses
   * const nutritionApiResponse = await prisma.nutritionApiResponse.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NutritionApiResponses and only return the `id`
   * const nutritionApiResponseWithIdOnly = await prisma.nutritionApiResponse.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NutritionApiResponseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NutritionApiResponseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NutritionApiResponse.
   * @param {NutritionApiResponseUpsertArgs} args - Arguments to update or create a NutritionApiResponse.
   * @example
   * // Update or create a NutritionApiResponse
   * const nutritionApiResponse = await prisma.nutritionApiResponse.upsert({
   *   create: {
   *     // ... data to create a NutritionApiResponse
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NutritionApiResponse we want to update
   *   }
   * })
   */
  upsert<T extends NutritionApiResponseUpsertArgs>(args: Prisma.SelectSubset<T, NutritionApiResponseUpsertArgs<ExtArgs>>): Prisma.Prisma__NutritionApiResponseClient<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NutritionApiResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionApiResponseCountArgs} args - Arguments to filter NutritionApiResponses to count.
   * @example
   * // Count the number of NutritionApiResponses
   * const count = await prisma.nutritionApiResponse.count({
   *   where: {
   *     // ... the filter for the NutritionApiResponses we want to count
   *   }
   * })
  **/
  count<T extends NutritionApiResponseCountArgs>(
    args?: Prisma.Subset<T, NutritionApiResponseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NutritionApiResponseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NutritionApiResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionApiResponseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NutritionApiResponseAggregateArgs>(args: Prisma.Subset<T, NutritionApiResponseAggregateArgs>): Prisma.PrismaPromise<GetNutritionApiResponseAggregateType<T>>

  /**
   * Group by NutritionApiResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionApiResponseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NutritionApiResponseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NutritionApiResponseGroupByArgs['orderBy'] }
      : { orderBy?: NutritionApiResponseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NutritionApiResponseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNutritionApiResponseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NutritionApiResponse model
 */
readonly fields: NutritionApiResponseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NutritionApiResponse.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NutritionApiResponseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.NutritionApiResponse$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NutritionApiResponse$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NutritionApiResponse model
 */
export interface NutritionApiResponseFieldRefs {
  readonly id: Prisma.FieldRef<"NutritionApiResponse", 'String'>
  readonly userId: Prisma.FieldRef<"NutritionApiResponse", 'String'>
  readonly query: Prisma.FieldRef<"NutritionApiResponse", 'String'>
  readonly rawResponse: Prisma.FieldRef<"NutritionApiResponse", 'Json'>
  readonly itemCount: Prisma.FieldRef<"NutritionApiResponse", 'Int'>
  readonly createdAt: Prisma.FieldRef<"NutritionApiResponse", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NutritionApiResponse findUnique
 */
export type NutritionApiResponseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  /**
   * Filter, which NutritionApiResponse to fetch.
   */
  where: Prisma.NutritionApiResponseWhereUniqueInput
}

/**
 * NutritionApiResponse findUniqueOrThrow
 */
export type NutritionApiResponseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  /**
   * Filter, which NutritionApiResponse to fetch.
   */
  where: Prisma.NutritionApiResponseWhereUniqueInput
}

/**
 * NutritionApiResponse findFirst
 */
export type NutritionApiResponseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  /**
   * Filter, which NutritionApiResponse to fetch.
   */
  where?: Prisma.NutritionApiResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NutritionApiResponses to fetch.
   */
  orderBy?: Prisma.NutritionApiResponseOrderByWithRelationInput | Prisma.NutritionApiResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NutritionApiResponses.
   */
  cursor?: Prisma.NutritionApiResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NutritionApiResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NutritionApiResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NutritionApiResponses.
   */
  distinct?: Prisma.NutritionApiResponseScalarFieldEnum | Prisma.NutritionApiResponseScalarFieldEnum[]
}

/**
 * NutritionApiResponse findFirstOrThrow
 */
export type NutritionApiResponseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  /**
   * Filter, which NutritionApiResponse to fetch.
   */
  where?: Prisma.NutritionApiResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NutritionApiResponses to fetch.
   */
  orderBy?: Prisma.NutritionApiResponseOrderByWithRelationInput | Prisma.NutritionApiResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NutritionApiResponses.
   */
  cursor?: Prisma.NutritionApiResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NutritionApiResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NutritionApiResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NutritionApiResponses.
   */
  distinct?: Prisma.NutritionApiResponseScalarFieldEnum | Prisma.NutritionApiResponseScalarFieldEnum[]
}

/**
 * NutritionApiResponse findMany
 */
export type NutritionApiResponseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  /**
   * Filter, which NutritionApiResponses to fetch.
   */
  where?: Prisma.NutritionApiResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NutritionApiResponses to fetch.
   */
  orderBy?: Prisma.NutritionApiResponseOrderByWithRelationInput | Prisma.NutritionApiResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NutritionApiResponses.
   */
  cursor?: Prisma.NutritionApiResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NutritionApiResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NutritionApiResponses.
   */
  skip?: number
  distinct?: Prisma.NutritionApiResponseScalarFieldEnum | Prisma.NutritionApiResponseScalarFieldEnum[]
}

/**
 * NutritionApiResponse create
 */
export type NutritionApiResponseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  /**
   * The data needed to create a NutritionApiResponse.
   */
  data: Prisma.XOR<Prisma.NutritionApiResponseCreateInput, Prisma.NutritionApiResponseUncheckedCreateInput>
}

/**
 * NutritionApiResponse createMany
 */
export type NutritionApiResponseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NutritionApiResponses.
   */
  data: Prisma.NutritionApiResponseCreateManyInput | Prisma.NutritionApiResponseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NutritionApiResponse createManyAndReturn
 */
export type NutritionApiResponseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * The data used to create many NutritionApiResponses.
   */
  data: Prisma.NutritionApiResponseCreateManyInput | Prisma.NutritionApiResponseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * NutritionApiResponse update
 */
export type NutritionApiResponseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  /**
   * The data needed to update a NutritionApiResponse.
   */
  data: Prisma.XOR<Prisma.NutritionApiResponseUpdateInput, Prisma.NutritionApiResponseUncheckedUpdateInput>
  /**
   * Choose, which NutritionApiResponse to update.
   */
  where: Prisma.NutritionApiResponseWhereUniqueInput
}

/**
 * NutritionApiResponse updateMany
 */
export type NutritionApiResponseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NutritionApiResponses.
   */
  data: Prisma.XOR<Prisma.NutritionApiResponseUpdateManyMutationInput, Prisma.NutritionApiResponseUncheckedUpdateManyInput>
  /**
   * Filter which NutritionApiResponses to update
   */
  where?: Prisma.NutritionApiResponseWhereInput
  /**
   * Limit how many NutritionApiResponses to update.
   */
  limit?: number
}

/**
 * NutritionApiResponse updateManyAndReturn
 */
export type NutritionApiResponseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * The data used to update NutritionApiResponses.
   */
  data: Prisma.XOR<Prisma.NutritionApiResponseUpdateManyMutationInput, Prisma.NutritionApiResponseUncheckedUpdateManyInput>
  /**
   * Filter which NutritionApiResponses to update
   */
  where?: Prisma.NutritionApiResponseWhereInput
  /**
   * Limit how many NutritionApiResponses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * NutritionApiResponse upsert
 */
export type NutritionApiResponseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  /**
   * The filter to search for the NutritionApiResponse to update in case it exists.
   */
  where: Prisma.NutritionApiResponseWhereUniqueInput
  /**
   * In case the NutritionApiResponse found by the `where` argument doesn't exist, create a new NutritionApiResponse with this data.
   */
  create: Prisma.XOR<Prisma.NutritionApiResponseCreateInput, Prisma.NutritionApiResponseUncheckedCreateInput>
  /**
   * In case the NutritionApiResponse was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NutritionApiResponseUpdateInput, Prisma.NutritionApiResponseUncheckedUpdateInput>
}

/**
 * NutritionApiResponse delete
 */
export type NutritionApiResponseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  /**
   * Filter which NutritionApiResponse to delete.
   */
  where: Prisma.NutritionApiResponseWhereUniqueInput
}

/**
 * NutritionApiResponse deleteMany
 */
export type NutritionApiResponseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NutritionApiResponses to delete
   */
  where?: Prisma.NutritionApiResponseWhereInput
  /**
   * Limit how many NutritionApiResponses to delete.
   */
  limit?: number
}

/**
 * NutritionApiResponse.user
 */
export type NutritionApiResponse$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * NutritionApiResponse without action
 */
export type NutritionApiResponseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
}
