
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserAvgAggregateOutputType = {
  age: number | null
  weight: number | null
  height: number | null
  recommendedCalories: number | null
}

export type UserSumAggregateOutputType = {
  age: number | null
  weight: number | null
  height: number | null
  recommendedCalories: number | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  email: string | null
  passwordHash: string | null
  firstName: string | null
  lastName: string | null
  createdAt: Date | null
  updatedAt: Date | null
  age: number | null
  weight: number | null
  height: number | null
  gender: $Enums.Gender | null
  activityLevel: $Enums.ActivityLevel | null
  primaryGoal: $Enums.PrimaryGoal | null
  dietaryRestrictions: string | null
  recommendedCalories: number | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  email: string | null
  passwordHash: string | null
  firstName: string | null
  lastName: string | null
  createdAt: Date | null
  updatedAt: Date | null
  age: number | null
  weight: number | null
  height: number | null
  gender: $Enums.Gender | null
  activityLevel: $Enums.ActivityLevel | null
  primaryGoal: $Enums.PrimaryGoal | null
  dietaryRestrictions: string | null
  recommendedCalories: number | null
}

export type UserCountAggregateOutputType = {
  id: number
  email: number
  passwordHash: number
  firstName: number
  lastName: number
  createdAt: number
  updatedAt: number
  age: number
  weight: number
  height: number
  gender: number
  activityLevel: number
  primaryGoal: number
  dietaryRestrictions: number
  recommendedCalories: number
  _all: number
}


export type UserAvgAggregateInputType = {
  age?: true
  weight?: true
  height?: true
  recommendedCalories?: true
}

export type UserSumAggregateInputType = {
  age?: true
  weight?: true
  height?: true
  recommendedCalories?: true
}

export type UserMinAggregateInputType = {
  id?: true
  email?: true
  passwordHash?: true
  firstName?: true
  lastName?: true
  createdAt?: true
  updatedAt?: true
  age?: true
  weight?: true
  height?: true
  gender?: true
  activityLevel?: true
  primaryGoal?: true
  dietaryRestrictions?: true
  recommendedCalories?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  email?: true
  passwordHash?: true
  firstName?: true
  lastName?: true
  createdAt?: true
  updatedAt?: true
  age?: true
  weight?: true
  height?: true
  gender?: true
  activityLevel?: true
  primaryGoal?: true
  dietaryRestrictions?: true
  recommendedCalories?: true
}

export type UserCountAggregateInputType = {
  id?: true
  email?: true
  passwordHash?: true
  firstName?: true
  lastName?: true
  createdAt?: true
  updatedAt?: true
  age?: true
  weight?: true
  height?: true
  gender?: true
  activityLevel?: true
  primaryGoal?: true
  dietaryRestrictions?: true
  recommendedCalories?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _avg?: UserAvgAggregateInputType
  _sum?: UserSumAggregateInputType
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  email: string
  passwordHash: string
  firstName: string | null
  lastName: string | null
  createdAt: Date
  updatedAt: Date
  age: number | null
  weight: number | null
  height: number | null
  gender: $Enums.Gender | null
  activityLevel: $Enums.ActivityLevel | null
  primaryGoal: $Enums.PrimaryGoal | null
  dietaryRestrictions: string | null
  recommendedCalories: number | null
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  email?: Prisma.StringFilter<"User"> | string
  passwordHash?: Prisma.StringFilter<"User"> | string
  firstName?: Prisma.StringNullableFilter<"User"> | string | null
  lastName?: Prisma.StringNullableFilter<"User"> | string | null
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  age?: Prisma.IntNullableFilter<"User"> | number | null
  weight?: Prisma.FloatNullableFilter<"User"> | number | null
  height?: Prisma.FloatNullableFilter<"User"> | number | null
  gender?: Prisma.EnumGenderNullableFilter<"User"> | $Enums.Gender | null
  activityLevel?: Prisma.EnumActivityLevelNullableFilter<"User"> | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.EnumPrimaryGoalNullableFilter<"User"> | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.StringNullableFilter<"User"> | string | null
  recommendedCalories?: Prisma.IntNullableFilter<"User"> | number | null
  foodLogs?: Prisma.FoodLogListRelationFilter
  aiAnalyses?: Prisma.AiAnalysisListRelationFilter
  nutritionApiResponses?: Prisma.NutritionApiResponseListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  firstName?: Prisma.SortOrderInput | Prisma.SortOrder
  lastName?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  age?: Prisma.SortOrderInput | Prisma.SortOrder
  weight?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  gender?: Prisma.SortOrderInput | Prisma.SortOrder
  activityLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  primaryGoal?: Prisma.SortOrderInput | Prisma.SortOrder
  dietaryRestrictions?: Prisma.SortOrderInput | Prisma.SortOrder
  recommendedCalories?: Prisma.SortOrderInput | Prisma.SortOrder
  foodLogs?: Prisma.FoodLogOrderByRelationAggregateInput
  aiAnalyses?: Prisma.AiAnalysisOrderByRelationAggregateInput
  nutritionApiResponses?: Prisma.NutritionApiResponseOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  passwordHash?: Prisma.StringFilter<"User"> | string
  firstName?: Prisma.StringNullableFilter<"User"> | string | null
  lastName?: Prisma.StringNullableFilter<"User"> | string | null
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  age?: Prisma.IntNullableFilter<"User"> | number | null
  weight?: Prisma.FloatNullableFilter<"User"> | number | null
  height?: Prisma.FloatNullableFilter<"User"> | number | null
  gender?: Prisma.EnumGenderNullableFilter<"User"> | $Enums.Gender | null
  activityLevel?: Prisma.EnumActivityLevelNullableFilter<"User"> | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.EnumPrimaryGoalNullableFilter<"User"> | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.StringNullableFilter<"User"> | string | null
  recommendedCalories?: Prisma.IntNullableFilter<"User"> | number | null
  foodLogs?: Prisma.FoodLogListRelationFilter
  aiAnalyses?: Prisma.AiAnalysisListRelationFilter
  nutritionApiResponses?: Prisma.NutritionApiResponseListRelationFilter
}, "id" | "email">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  firstName?: Prisma.SortOrderInput | Prisma.SortOrder
  lastName?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  age?: Prisma.SortOrderInput | Prisma.SortOrder
  weight?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  gender?: Prisma.SortOrderInput | Prisma.SortOrder
  activityLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  primaryGoal?: Prisma.SortOrderInput | Prisma.SortOrder
  dietaryRestrictions?: Prisma.SortOrderInput | Prisma.SortOrder
  recommendedCalories?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _avg?: Prisma.UserAvgOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
  _sum?: Prisma.UserSumOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  email?: Prisma.StringWithAggregatesFilter<"User"> | string
  passwordHash?: Prisma.StringWithAggregatesFilter<"User"> | string
  firstName?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  lastName?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  age?: Prisma.IntNullableWithAggregatesFilter<"User"> | number | null
  weight?: Prisma.FloatNullableWithAggregatesFilter<"User"> | number | null
  height?: Prisma.FloatNullableWithAggregatesFilter<"User"> | number | null
  gender?: Prisma.EnumGenderNullableWithAggregatesFilter<"User"> | $Enums.Gender | null
  activityLevel?: Prisma.EnumActivityLevelNullableWithAggregatesFilter<"User"> | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.EnumPrimaryGoalNullableWithAggregatesFilter<"User"> | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  recommendedCalories?: Prisma.IntNullableWithAggregatesFilter<"User"> | number | null
}

export type UserCreateInput = {
  id?: string
  email: string
  passwordHash: string
  firstName?: string | null
  lastName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  age?: number | null
  weight?: number | null
  height?: number | null
  gender?: $Enums.Gender | null
  activityLevel?: $Enums.ActivityLevel | null
  primaryGoal?: $Enums.PrimaryGoal | null
  dietaryRestrictions?: string | null
  recommendedCalories?: number | null
  foodLogs?: Prisma.FoodLogCreateNestedManyWithoutUserInput
  aiAnalyses?: Prisma.AiAnalysisCreateNestedManyWithoutUserInput
  nutritionApiResponses?: Prisma.NutritionApiResponseCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: string
  email: string
  passwordHash: string
  firstName?: string | null
  lastName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  age?: number | null
  weight?: number | null
  height?: number | null
  gender?: $Enums.Gender | null
  activityLevel?: $Enums.ActivityLevel | null
  primaryGoal?: $Enums.PrimaryGoal | null
  dietaryRestrictions?: string | null
  recommendedCalories?: number | null
  foodLogs?: Prisma.FoodLogUncheckedCreateNestedManyWithoutUserInput
  aiAnalyses?: Prisma.AiAnalysisUncheckedCreateNestedManyWithoutUserInput
  nutritionApiResponses?: Prisma.NutritionApiResponseUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  foodLogs?: Prisma.FoodLogUpdateManyWithoutUserNestedInput
  aiAnalyses?: Prisma.AiAnalysisUpdateManyWithoutUserNestedInput
  nutritionApiResponses?: Prisma.NutritionApiResponseUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  foodLogs?: Prisma.FoodLogUncheckedUpdateManyWithoutUserNestedInput
  aiAnalyses?: Prisma.AiAnalysisUncheckedUpdateManyWithoutUserNestedInput
  nutritionApiResponses?: Prisma.NutritionApiResponseUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: string
  email: string
  passwordHash: string
  firstName?: string | null
  lastName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  age?: number | null
  weight?: number | null
  height?: number | null
  gender?: $Enums.Gender | null
  activityLevel?: $Enums.ActivityLevel | null
  primaryGoal?: $Enums.PrimaryGoal | null
  dietaryRestrictions?: string | null
  recommendedCalories?: number | null
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  height?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  activityLevel?: Prisma.SortOrder
  primaryGoal?: Prisma.SortOrder
  dietaryRestrictions?: Prisma.SortOrder
  recommendedCalories?: Prisma.SortOrder
}

export type UserAvgOrderByAggregateInput = {
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  height?: Prisma.SortOrder
  recommendedCalories?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  height?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  activityLevel?: Prisma.SortOrder
  primaryGoal?: Prisma.SortOrder
  dietaryRestrictions?: Prisma.SortOrder
  recommendedCalories?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  height?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  activityLevel?: Prisma.SortOrder
  primaryGoal?: Prisma.SortOrder
  dietaryRestrictions?: Prisma.SortOrder
  recommendedCalories?: Prisma.SortOrder
}

export type UserSumOrderByAggregateInput = {
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  height?: Prisma.SortOrder
  recommendedCalories?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type UserNullableScalarRelationFilter = {
  is?: Prisma.UserWhereInput | null
  isNot?: Prisma.UserWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableEnumGenderFieldUpdateOperationsInput = {
  set?: $Enums.Gender | null
}

export type NullableEnumActivityLevelFieldUpdateOperationsInput = {
  set?: $Enums.ActivityLevel | null
}

export type NullableEnumPrimaryGoalFieldUpdateOperationsInput = {
  set?: $Enums.PrimaryGoal | null
}

export type UserCreateNestedOneWithoutFoodLogsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFoodLogsInput, Prisma.UserUncheckedCreateWithoutFoodLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFoodLogsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutFoodLogsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFoodLogsInput, Prisma.UserUncheckedCreateWithoutFoodLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFoodLogsInput
  upsert?: Prisma.UserUpsertWithoutFoodLogsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutFoodLogsInput, Prisma.UserUpdateWithoutFoodLogsInput>, Prisma.UserUncheckedUpdateWithoutFoodLogsInput>
}

export type UserCreateNestedOneWithoutAiAnalysesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAiAnalysesInput, Prisma.UserUncheckedCreateWithoutAiAnalysesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAiAnalysesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutAiAnalysesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAiAnalysesInput, Prisma.UserUncheckedCreateWithoutAiAnalysesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAiAnalysesInput
  upsert?: Prisma.UserUpsertWithoutAiAnalysesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutAiAnalysesInput, Prisma.UserUpdateWithoutAiAnalysesInput>, Prisma.UserUncheckedUpdateWithoutAiAnalysesInput>
}

export type UserCreateNestedOneWithoutNutritionApiResponsesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutNutritionApiResponsesInput, Prisma.UserUncheckedCreateWithoutNutritionApiResponsesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutNutritionApiResponsesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneWithoutNutritionApiResponsesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutNutritionApiResponsesInput, Prisma.UserUncheckedCreateWithoutNutritionApiResponsesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutNutritionApiResponsesInput
  upsert?: Prisma.UserUpsertWithoutNutritionApiResponsesInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutNutritionApiResponsesInput, Prisma.UserUpdateWithoutNutritionApiResponsesInput>, Prisma.UserUncheckedUpdateWithoutNutritionApiResponsesInput>
}

export type UserCreateWithoutFoodLogsInput = {
  id?: string
  email: string
  passwordHash: string
  firstName?: string | null
  lastName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  age?: number | null
  weight?: number | null
  height?: number | null
  gender?: $Enums.Gender | null
  activityLevel?: $Enums.ActivityLevel | null
  primaryGoal?: $Enums.PrimaryGoal | null
  dietaryRestrictions?: string | null
  recommendedCalories?: number | null
  aiAnalyses?: Prisma.AiAnalysisCreateNestedManyWithoutUserInput
  nutritionApiResponses?: Prisma.NutritionApiResponseCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutFoodLogsInput = {
  id?: string
  email: string
  passwordHash: string
  firstName?: string | null
  lastName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  age?: number | null
  weight?: number | null
  height?: number | null
  gender?: $Enums.Gender | null
  activityLevel?: $Enums.ActivityLevel | null
  primaryGoal?: $Enums.PrimaryGoal | null
  dietaryRestrictions?: string | null
  recommendedCalories?: number | null
  aiAnalyses?: Prisma.AiAnalysisUncheckedCreateNestedManyWithoutUserInput
  nutritionApiResponses?: Prisma.NutritionApiResponseUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutFoodLogsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutFoodLogsInput, Prisma.UserUncheckedCreateWithoutFoodLogsInput>
}

export type UserUpsertWithoutFoodLogsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutFoodLogsInput, Prisma.UserUncheckedUpdateWithoutFoodLogsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutFoodLogsInput, Prisma.UserUncheckedCreateWithoutFoodLogsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutFoodLogsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutFoodLogsInput, Prisma.UserUncheckedUpdateWithoutFoodLogsInput>
}

export type UserUpdateWithoutFoodLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiAnalyses?: Prisma.AiAnalysisUpdateManyWithoutUserNestedInput
  nutritionApiResponses?: Prisma.NutritionApiResponseUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutFoodLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiAnalyses?: Prisma.AiAnalysisUncheckedUpdateManyWithoutUserNestedInput
  nutritionApiResponses?: Prisma.NutritionApiResponseUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutAiAnalysesInput = {
  id?: string
  email: string
  passwordHash: string
  firstName?: string | null
  lastName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  age?: number | null
  weight?: number | null
  height?: number | null
  gender?: $Enums.Gender | null
  activityLevel?: $Enums.ActivityLevel | null
  primaryGoal?: $Enums.PrimaryGoal | null
  dietaryRestrictions?: string | null
  recommendedCalories?: number | null
  foodLogs?: Prisma.FoodLogCreateNestedManyWithoutUserInput
  nutritionApiResponses?: Prisma.NutritionApiResponseCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutAiAnalysesInput = {
  id?: string
  email: string
  passwordHash: string
  firstName?: string | null
  lastName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  age?: number | null
  weight?: number | null
  height?: number | null
  gender?: $Enums.Gender | null
  activityLevel?: $Enums.ActivityLevel | null
  primaryGoal?: $Enums.PrimaryGoal | null
  dietaryRestrictions?: string | null
  recommendedCalories?: number | null
  foodLogs?: Prisma.FoodLogUncheckedCreateNestedManyWithoutUserInput
  nutritionApiResponses?: Prisma.NutritionApiResponseUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutAiAnalysesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutAiAnalysesInput, Prisma.UserUncheckedCreateWithoutAiAnalysesInput>
}

export type UserUpsertWithoutAiAnalysesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutAiAnalysesInput, Prisma.UserUncheckedUpdateWithoutAiAnalysesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutAiAnalysesInput, Prisma.UserUncheckedCreateWithoutAiAnalysesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutAiAnalysesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutAiAnalysesInput, Prisma.UserUncheckedUpdateWithoutAiAnalysesInput>
}

export type UserUpdateWithoutAiAnalysesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  foodLogs?: Prisma.FoodLogUpdateManyWithoutUserNestedInput
  nutritionApiResponses?: Prisma.NutritionApiResponseUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutAiAnalysesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  foodLogs?: Prisma.FoodLogUncheckedUpdateManyWithoutUserNestedInput
  nutritionApiResponses?: Prisma.NutritionApiResponseUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutNutritionApiResponsesInput = {
  id?: string
  email: string
  passwordHash: string
  firstName?: string | null
  lastName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  age?: number | null
  weight?: number | null
  height?: number | null
  gender?: $Enums.Gender | null
  activityLevel?: $Enums.ActivityLevel | null
  primaryGoal?: $Enums.PrimaryGoal | null
  dietaryRestrictions?: string | null
  recommendedCalories?: number | null
  foodLogs?: Prisma.FoodLogCreateNestedManyWithoutUserInput
  aiAnalyses?: Prisma.AiAnalysisCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutNutritionApiResponsesInput = {
  id?: string
  email: string
  passwordHash: string
  firstName?: string | null
  lastName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  age?: number | null
  weight?: number | null
  height?: number | null
  gender?: $Enums.Gender | null
  activityLevel?: $Enums.ActivityLevel | null
  primaryGoal?: $Enums.PrimaryGoal | null
  dietaryRestrictions?: string | null
  recommendedCalories?: number | null
  foodLogs?: Prisma.FoodLogUncheckedCreateNestedManyWithoutUserInput
  aiAnalyses?: Prisma.AiAnalysisUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutNutritionApiResponsesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutNutritionApiResponsesInput, Prisma.UserUncheckedCreateWithoutNutritionApiResponsesInput>
}

export type UserUpsertWithoutNutritionApiResponsesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutNutritionApiResponsesInput, Prisma.UserUncheckedUpdateWithoutNutritionApiResponsesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutNutritionApiResponsesInput, Prisma.UserUncheckedCreateWithoutNutritionApiResponsesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutNutritionApiResponsesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutNutritionApiResponsesInput, Prisma.UserUncheckedUpdateWithoutNutritionApiResponsesInput>
}

export type UserUpdateWithoutNutritionApiResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  foodLogs?: Prisma.FoodLogUpdateManyWithoutUserNestedInput
  aiAnalyses?: Prisma.AiAnalysisUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutNutritionApiResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weight?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gender?: Prisma.NullableEnumGenderFieldUpdateOperationsInput | $Enums.Gender | null
  activityLevel?: Prisma.NullableEnumActivityLevelFieldUpdateOperationsInput | $Enums.ActivityLevel | null
  primaryGoal?: Prisma.NullableEnumPrimaryGoalFieldUpdateOperationsInput | $Enums.PrimaryGoal | null
  dietaryRestrictions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recommendedCalories?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  foodLogs?: Prisma.FoodLogUncheckedUpdateManyWithoutUserNestedInput
  aiAnalyses?: Prisma.AiAnalysisUncheckedUpdateManyWithoutUserNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  foodLogs: number
  aiAnalyses: number
  nutritionApiResponses: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  foodLogs?: boolean | UserCountOutputTypeCountFoodLogsArgs
  aiAnalyses?: boolean | UserCountOutputTypeCountAiAnalysesArgs
  nutritionApiResponses?: boolean | UserCountOutputTypeCountNutritionApiResponsesArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountFoodLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FoodLogWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountAiAnalysesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AiAnalysisWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountNutritionApiResponsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NutritionApiResponseWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  passwordHash?: boolean
  firstName?: boolean
  lastName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  age?: boolean
  weight?: boolean
  height?: boolean
  gender?: boolean
  activityLevel?: boolean
  primaryGoal?: boolean
  dietaryRestrictions?: boolean
  recommendedCalories?: boolean
  foodLogs?: boolean | Prisma.User$foodLogsArgs<ExtArgs>
  aiAnalyses?: boolean | Prisma.User$aiAnalysesArgs<ExtArgs>
  nutritionApiResponses?: boolean | Prisma.User$nutritionApiResponsesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  passwordHash?: boolean
  firstName?: boolean
  lastName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  age?: boolean
  weight?: boolean
  height?: boolean
  gender?: boolean
  activityLevel?: boolean
  primaryGoal?: boolean
  dietaryRestrictions?: boolean
  recommendedCalories?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  passwordHash?: boolean
  firstName?: boolean
  lastName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  age?: boolean
  weight?: boolean
  height?: boolean
  gender?: boolean
  activityLevel?: boolean
  primaryGoal?: boolean
  dietaryRestrictions?: boolean
  recommendedCalories?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  email?: boolean
  passwordHash?: boolean
  firstName?: boolean
  lastName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  age?: boolean
  weight?: boolean
  height?: boolean
  gender?: boolean
  activityLevel?: boolean
  primaryGoal?: boolean
  dietaryRestrictions?: boolean
  recommendedCalories?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "passwordHash" | "firstName" | "lastName" | "createdAt" | "updatedAt" | "age" | "weight" | "height" | "gender" | "activityLevel" | "primaryGoal" | "dietaryRestrictions" | "recommendedCalories", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  foodLogs?: boolean | Prisma.User$foodLogsArgs<ExtArgs>
  aiAnalyses?: boolean | Prisma.User$aiAnalysesArgs<ExtArgs>
  nutritionApiResponses?: boolean | Prisma.User$nutritionApiResponsesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    foodLogs: Prisma.$FoodLogPayload<ExtArgs>[]
    aiAnalyses: Prisma.$AiAnalysisPayload<ExtArgs>[]
    nutritionApiResponses: Prisma.$NutritionApiResponsePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    passwordHash: string
    firstName: string | null
    lastName: string | null
    createdAt: Date
    updatedAt: Date
    age: number | null
    weight: number | null
    height: number | null
    gender: $Enums.Gender | null
    activityLevel: $Enums.ActivityLevel | null
    primaryGoal: $Enums.PrimaryGoal | null
    dietaryRestrictions: string | null
    recommendedCalories: number | null
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  foodLogs<T extends Prisma.User$foodLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$foodLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FoodLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  aiAnalyses<T extends Prisma.User$aiAnalysesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$aiAnalysesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  nutritionApiResponses<T extends Prisma.User$nutritionApiResponsesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$nutritionApiResponsesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NutritionApiResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly passwordHash: Prisma.FieldRef<"User", 'String'>
  readonly firstName: Prisma.FieldRef<"User", 'String'>
  readonly lastName: Prisma.FieldRef<"User", 'String'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly age: Prisma.FieldRef<"User", 'Int'>
  readonly weight: Prisma.FieldRef<"User", 'Float'>
  readonly height: Prisma.FieldRef<"User", 'Float'>
  readonly gender: Prisma.FieldRef<"User", 'Gender'>
  readonly activityLevel: Prisma.FieldRef<"User", 'ActivityLevel'>
  readonly primaryGoal: Prisma.FieldRef<"User", 'PrimaryGoal'>
  readonly dietaryRestrictions: Prisma.FieldRef<"User", 'String'>
  readonly recommendedCalories: Prisma.FieldRef<"User", 'Int'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.foodLogs
 */
export type User$foodLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FoodLog
   */
  select?: Prisma.FoodLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FoodLog
   */
  omit?: Prisma.FoodLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoodLogInclude<ExtArgs> | null
  where?: Prisma.FoodLogWhereInput
  orderBy?: Prisma.FoodLogOrderByWithRelationInput | Prisma.FoodLogOrderByWithRelationInput[]
  cursor?: Prisma.FoodLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FoodLogScalarFieldEnum | Prisma.FoodLogScalarFieldEnum[]
}

/**
 * User.aiAnalyses
 */
export type User$aiAnalysesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  where?: Prisma.AiAnalysisWhereInput
  orderBy?: Prisma.AiAnalysisOrderByWithRelationInput | Prisma.AiAnalysisOrderByWithRelationInput[]
  cursor?: Prisma.AiAnalysisWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AiAnalysisScalarFieldEnum | Prisma.AiAnalysisScalarFieldEnum[]
}

/**
 * User.nutritionApiResponses
 */
export type User$nutritionApiResponsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionApiResponse
   */
  select?: Prisma.NutritionApiResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionApiResponse
   */
  omit?: Prisma.NutritionApiResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionApiResponseInclude<ExtArgs> | null
  where?: Prisma.NutritionApiResponseWhereInput
  orderBy?: Prisma.NutritionApiResponseOrderByWithRelationInput | Prisma.NutritionApiResponseOrderByWithRelationInput[]
  cursor?: Prisma.NutritionApiResponseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NutritionApiResponseScalarFieldEnum | Prisma.NutritionApiResponseScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
