
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
  PREFER_NOT_TO_SAY: 'PREFER_NOT_TO_SAY'
} as const

export type Gender = (typeof Gender)[keyof typeof Gender]


export const ActivityLevel = {
  SEDENTARY: 'SEDENTARY',
  LIGHTLY_ACTIVE: 'LIGHTLY_ACTIVE',
  MODERATELY_ACTIVE: 'MODERATELY_ACTIVE',
  VERY_ACTIVE: 'VERY_ACTIVE',
  EXTRA_ACTIVE: 'EXTRA_ACTIVE'
} as const

export type ActivityLevel = (typeof ActivityLevel)[keyof typeof ActivityLevel]


export const PrimaryGoal = {
  WEIGHT_LOSS: 'WEIGHT_LOSS',
  MUSCLE_GAIN: 'MUSCLE_GAIN',
  MAINTENANCE: 'MAINTENANCE',
  IMPROVED_HEALTH: 'IMPROVED_HEALTH',
  ATHLETIC_PERFORMANCE: 'ATHLETIC_PERFORMANCE'
} as const

export type PrimaryGoal = (typeof PrimaryGoal)[keyof typeof PrimaryGoal]


export const EmotionalState = {
  STRESS: 'STRESS',
  BOREDOM: 'BOREDOM',
  HAPPINESS: 'HAPPINESS',
  SADNESS: 'SADNESS',
  NEUTRAL: 'NEUTRAL'
} as const

export type EmotionalState = (typeof EmotionalState)[keyof typeof EmotionalState]


export const EatingContext = {
  HOME: 'HOME',
  WORK: 'WORK',
  SOCIAL: 'SOCIAL',
  RESTAURANT: 'RESTAURANT'
} as const

export type EatingContext = (typeof EatingContext)[keyof typeof EatingContext]
